package com.orange.formationjava.trier;

public class Person implements Comparable<Person> {

	private final String mFirstName;
	private final String mLastName;
	private Integer mAge;

	public Person(String firstName, String lastName, int age) {
		mFirstName = firstName;
		mLastName = lastName;
		mAge = age;
	}

	public String getLastName() {
		return mLastName;
	}

	public String getFirstName() {
		return mFirstName;
	}

	public Integer getAge() {
		return mAge;
	}

	public void setAge(int age) {
		mAge = age;
	}

	@Override
	public String toString() {
		return "Person [prénom='" + mFirstName + "', nom='" + mLastName + ", age=" + mAge + "]";
	}

	@Override
	public int compareTo(Person other) {
		// Comparaison sur le nom
		int compareNom = mLastName.compareTo(other.mLastName);
		if (compareNom == 0)  {
			// Si égalité sur le nom: comparaison sur le prénom
			return mFirstName.compareTo(other.mFirstName);
		}
		return compareNom;
	}
	
	// auto generated by Eclipse IDE
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((mAge == null) ? 0 : mAge.hashCode());
		result = prime * result + ((mFirstName == null) ? 0 : mFirstName.hashCode());
		result = prime * result + ((mLastName == null) ? 0 : mLastName.hashCode());
		return result;
	}

	// auto generated by Eclipse IDE
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Person other = (Person) obj;
		if (mAge == null) {
			if (other.mAge != null)
				return false;
		} else if (!mAge.equals(other.mAge))
			return false;
		if (mFirstName == null) {
			if (other.mFirstName != null)
				return false;
		} else if (!mFirstName.equals(other.mFirstName))
			return false;
		if (mLastName == null) {
			if (other.mLastName != null)
				return false;
		} else if (!mLastName.equals(other.mLastName))
			return false;
		return true;
	}


}
